#!/bin/bash
if [ -t 0 ]
then
    if [[ "X$1" == "X" ]]
    then
        echo "Converts tab-delimited to columnar format for easy viewing"
	echo "Usage: d2l <tab delimited file>"
	echo "       cat <tab delimited file> | d2l"
	exit 1
    fi
    cat $@ | column -s $'\t' -t
else
    column -s $'\t' -t
fi
